### ISSUE TITLE
Diff output is backwards

### ISSUE THREAD

**Issue by jtdowney** [pplr/redmine-libsvn#1]
After we started using the libsvn plugin we noticed our diff views were backwards. The text being added was in red and the text being removed was green. When I turned off the plugin it changed back to the correct view that redmine ships with.

**Comment by victornoel** [comment]
I second that

**Comment by pplr** [comment]
I fixed this issue in b9c30d8c2ff0977222a85d81ddede8a2529ed467
Thanks for reporting.

**Comment by panga** [comment]
Its fixed.
