### ISSUE TITLE
Unable to view earlier versions of removed files

### ISSUE THREAD

**Issue by ghost** [pplr/redmine-libsvn#11]
Removing a file and trying to view it from an earlier revision causes internal error.

Expected result: Show the history of the file
Observer result: Internal error

Steps to reproduce:
1. Remove a file and commit the changes
2. Navigate to redmine's repository-page and change to a specific revision (newest - 1)
3. In the file view, click on the file you removed
   -> Internal error

URL should look something like this:
https://domain/redmine/projects/project_name/repository/revisions/revision_number/changes/filename

**Comment by pplr** [comment]
Invoke #log with right peg_revision parameter. closed by 0662d754198723b6e8ad9c941d883fc5691b94f9

**Comment by pplr** [comment]
Thanks for reporting this issue. I commited a bugfix. Keep me informed if it did not resolve your problem.

**Comment by ghost** [comment]
This did indeed fix the issue, awesome work!

Thanks for to quick fix. :)

**Comment by pplr** [comment]
Thanks for testing it so quick !
