### ISSUE TITLE
Can't navigate in subversion if the address of the repository is not the root

### ISSUE THREAD

**Issue by victornoel** [pplr/redmine-libsvn#2]
Hello, I reported this bug at redmine's bugtracker but I think this is from this plugin, you can see the full description there:
http://www.redmine.org/issues/4879

Thanks

**Comment by pplr** [comment]
Hello,
I can't reproduce the bug your describing. Can you give me more details on the version of redmine you use ? Can you observe that disabling the libsvn plugin fixes the bug ?

**Comment by victornoel** [comment]
Hello,

The people who manage the server are not there currently, so I will come back to you next week when I have more information for you :)

Thank you

**Comment by victornoel** [comment]
Hello, finally some answers:
We are using Redmine 0.9.2 and disabling the plugin fixes this bug.

Thank you.

**Comment by panga** [comment]
Hi,

I had the same problem but fixed it by changing the method "def entries".
The error was in :name and :path entries.

:name => URI.unescape(path),
:path => ((path_argument.empty? ? "" : "#{path_argument}/") + path),

Where "path_argument" is the "path" given by argument.

**Comment by pplr** [comment]
Fix malformed entries path for non root repositories. closed by cecfe06405cf01c2284b1a67beae74c3aa747c83
Fix fetch_changeset exception when tracking a folder created after the
200th revision. closed by cecfe06405cf01c2284b1a67beae74c3aa747c83

**Comment by pplr** [comment]
Thanks for reporting this bug.
