### ISSUE TITLE
rake redmine:fetch_changesets error!

### ISSUE THREAD

**Issue by panga** [pplr/redmine-libsvn#3]
The plugin doesn't have catch exception in the method "def revisions", when the RedMine fetch a changeset of a non root directory, the ruby svn bindings returns an exception because the path doesn't exists in that revision.

To fix, i add the line "rescue" at the end of method "def revisions".

def revisions
...
- rescue
  end

**Comment by pplr** [comment]
Could you explain the exact procedure to reproduce the bug you describe ?

**Comment by panga** [comment]
I think is same problem that issue #5 "Problems browsing empty repository".
When the redmine try to get a log from a path in repository that doesn't have the revision specified, the plugin doesn't catch the exception.

Example: http://svn.company.com/svn/products/myproduct/application
This url was created in revision 1000, but Redmine fetch_changesets try to get from revision 1 to HEAD...DANN! exception and the command fails.

**Comment by pplr** [comment]
Fix malformed entries path for non root repositories. closed by cecfe06405cf01c2284b1a67beae74c3aa747c83
Fix fetch_changeset exception when tracking a folder created after the
200th revision. closed by cecfe06405cf01c2284b1a67beae74c3aa747c83

**Comment by pplr** [comment]
Thanks for reporting this bug.
