### ISSUE TITLE
Problem with secured connection(https://) repository url

### ISSUE THREAD

**Issue by xyz37** [pplr/redmine-libsvn#6]
In my case subversion repository start with https://
then I trusted repository site's cretification.

But redmine(without redmine-libsvn plugin) does not working on https repository url
then I patch on my own 
modified '<redmine root>/lib/redmine/scm/adapters/subversion_adapter.rb' 
--no-auth-cache --non-interactive
to
--trust-server-cert --no-auth-cache --non-interactive
(http://www.redmine.org/wiki/redmine/FAQ#I-cant-browse-my-svn-repository-through-redmine)

and redmine(with redmine-libsvn plugin) does not working on https repository url too.
What should I do?
# My error messages are :

Svn::Error::RaDavRequestFailed (C:\Projects\subversion-1.6.6\subversion\libsvn_ra_neon\util.c:604: Svn::Error::RaDavRequestFailed: OPTIONS of 'https://RedmineTest/svn/Test': Server certificate verification failed: issuer is not trusted (https://RedmineTest)):
  D:/CI/Ruby/lib/ruby/site_ruby/1.8/svn/util.rb:86:in `svn_client_info2'
  D:/CI/Ruby/lib/ruby/site_ruby/1.8/svn/util.rb:86:in`info2'
  D:/CI/Ruby/lib/ruby/site_ruby/1.8/svn/client.rb:446:in `info'
  lib/redmine/scm/adapters/abstract_adapter.rb:162:in`retrieve_root_url'
  lib/redmine/scm/adapters/abstract_adapter.rb:54:in `initialize'
  app/models/repository.rb:41:in`new'
  app/models/repository.rb:41:in `scm'
  app/models/repository.rb:75:in`default_branch'
  app/controllers/repositories_controller.rb:205:in `find_repository'
  D:/CI/Ruby/lib/ruby/1.8/webrick/httpserver.rb:104:in`service'
  D:/CI/Ruby/lib/ruby/1.8/webrick/httpserver.rb:65:in `run'
  D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:173:in`start_thread'
  D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:162:in `start'
  D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:162:in`start_thread'
  D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:95:in `start'
  D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:92:in`each'
  D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:92:in `start'
  D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:23:in`start'
  D:/CI/Ruby/lib/ruby/1.8/webrick/server.rb:82:in `start'
# Rendering rescues/layout (internal_server_error)

My 
Subversion server 1.6.6
Subversion client 1.6.6
Ruby bindings for Subversion on Win32. (svn-win32-1.6.6_rb.zip) in http://subversion.tigris.org/servlets/ProjectDocumentList?folderID=8100
and "run irb and test with: require ‘svn/core’" command result true

**Comment by pplr** [comment]
Add a plugin setting to allow accessing subversion repositories with invalid SSL certificate. closed by a88f79cf7253f4931691625ca74192fee2a7cc4c

**Comment by pplr** [comment]
I added a plugin setting to disable SSL server certificate validation. Bypassing SSL certificate validation is almost the same thing as disabling SSL. I recommend to you to configure the web server hosting subversion repositories with a valid certificate. If you don't want to buy a certificate issued by a 'valid' CA, you can obtain one by cacert.org and add the cacert root certificate in the list of valid CAs of the Windows hosting your Redmine instance.

**Comment by xyz37** [comment]
Thanks a lot of your efforts and quick fixes
and Korean language file shared from http://github.com/downloads/xyz37/redmine_plugins/redmine_libsvn_ko.yml

**Comment by xyz37** [comment]
Install for windows environment step update wiki
but not good at English. :-)

**Comment by pplr** [comment]
Thanks for your contribution. I don't understand the purpose of the language file you wrote. The terms included are not present in Redmine or in the libsvn plugin. The only sentence I used in the plugin is "Trust invalid SSL server certificates". If you can translate it in korean, I will add the korean language file in the plugin.

**Comment by xyz37** [comment]
Sorry above link is wrong.
http://github.com/downloads/xyz37/redmine_plugins/redmine_libsvn_ko.yml is correct link
