### ISSUE TITLE
The plugin does not work well in development mode

### ISSUE THREAD

**Issue by ebastien** [pplr/redmine-libsvn#7]
Hi,
First, thanks a lot for this nice plugin !
I don't know if it is a problem with Redmine or the plugin itself, but when running Redmine in development mode, the libsvn adapter is only used on the first request received by the server. All other requests are processed by the 'shellout'  adapter.

-- Emmanuel

**Comment by pplr** [comment]
Hi,
I fixed this issue yesterday in 10818bfa6b4daa63ab03a337d7dfa3bce048a9ac.
