### ISSUE TITLE
can't use it

### ISSUE THREAD

**Issue by stattrak-dragonlore** [pplr/redmine-libsvn#8]
I installed libsvn-ruby and this plugin.
but when I browse a repository,  I got a 500 page, the production log shows:

53508 NameError (uninitialized constant Svn::Error::FsNotFound):
53509   app/models/repository.rb:63:in `entries'
53510   app/controllers/repositories_controller.rb:72:in`show'
53511   /usr/lib/ruby/1.8/thread.rb:135:in `synchronize'
53512   public/dispatch.fcgi:24
53513
53514 Rendering /home/redmine/public/500.html (500 Internal Server Error)
how to fix it?

**Comment by pplr** [comment]
I cannot reproduce this error. Can you give me more details on your Redmine installation :
- redmine version
- libsvn version
- type of subversion repositories (local, http, https, ...)

**Comment by stattrak-dragonlore** [comment]
redmine : 0.9-stable, Revision: 3629
libsvn_swig_ruby-1.so.1 -> libsvn_swig_ruby-1.so.1.0.0
repositories: https

os: debian lenny.

no problem using svn command..
