### ISSUE TITLE
Doesn't work with Postgres

### ISSUE THREAD

**Issue by pauleil** [pplr/redmine-libsvn#9]
The plugin throws error 500 when I try to browse my repository. Running Redmine 0.9.6 and Postgres 8.4.4.

Processing RepositoriesController#show (for 1.2.3.4 at 2010-07-13 21:06:52) [GET]
  Parameters: {"action"=>"show", "id"=>"myproject", "controller"=>"repositories"}

ActiveRecord::StatementInvalid (PGError: ERROR:  operator does not exist: character varying = integer
LINE 1: ... FROM "changesets" WHERE ("changesets"."revision" IN (1189,1...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
: SELECT \* FROM "changesets" WHERE ("changesets"."revision" IN (1189,1188,1187,1186,1185,1184,1183,1182,1181,1180)) AND ("changesets".repository_id = 5)  ORDER BY committed_on DESC, changesets.committed_on DESC, changesets.id DESC):
  app/models/repository/subversion.rb:35:in `latest_changesets'

Adding single quotation marks around integers in the IN () part of the SELECT statement resolves the issue.

Could you please issue a patch that makes it possible to use with Postgres?

Thanks!

**Comment by pplr** [comment]
Fix compatibility issue with postgreSQL.
closed by 3baaf2209a95c2d962847e91d0247bfd0d51f14b

**Comment by pauleil** [comment]
Thanks, works now!
